### ISSUE TITLE
能写个中文的文档么

### ISSUE THREAD

**Issue by Cashdispenser** [Kelin-Hong/TranslucentBar#1]

**Comment by Kelin-Hong** [comment]
你好，本来有考虑写个中文使用文档，但是发现使用相对比较简单，基本就是调用translucent和transparent 方法就可以了，所以目前应该是没打算写中文文档的。😁 使用代码参照：
`  TranslucentBarManager translucentBarManager = new TranslucentBarManager(this);
        translucentBarManager.translucent(this);
        //or translucentBarManager.transparent(this);`
