### ISSUE TITLE
没用啊？

### ISSUE THREAD

**Issue by Shyky** [Kelin-Hong/TranslucentBar#4]

**Comment by Kelin-Hong** [comment]
什么问题，贴出来看看可能是使用的方式不对

**Comment by Shyky** [comment]
我在style里面设置了，状态栏不正常

**Comment by Kelin-Hong** [comment]
我们自己项目也用着，库应该还相当稳定的。你把布局代码贴出来看看，我看看是不是有bug？

**Comment by Shyky** [comment]
不是在style里声明就行了吗

**Comment by Kelin-Hong** [comment]
style里声明后只是设置了透明状态栏模式，相当于你可以利用状态栏下面的空间，但是你还要做好状态栏适配，比如不然toolbar 被状态栏挡住之类
