### ISSUE TITLE
fragment沉浸式感觉有问题

### ISSUE THREAD

**Issue by zengcanxiang** [Kelin-Hong/TranslucentBar#5]
一般项目中fragment不会replace，我hide，只有一个用沉浸式，结果三个都沉浸式了。然后其他不需要加沉浸式的布局上加fitsSystemWindows也没有用
而且fragment上，沉浸式总是布局上到了状态栏，不知道为啥。在<FrameLayout>标签上加fitsSystemWindows，就会丢失沉浸式效果。在fragment的布局里加，就没有效果。布局还是上到了状态栏

**Comment by Kelin-Hong** [comment]
1、状态栏属于theme 的设置项，theme是跟着activity走的，所以同一个Activity的Fragment 是共用一个theme，所以 ”只有一个用沉浸式，结果三个都沉浸式了“
2、不需要在xml 文件添加 fitsSystemWindows，在其他的Fragment的onCreateView 方法中调用  translucentBarManager.transparent(this, view, color) 就可以了
 你再试试 有什么问题，期待反馈

**Comment by zengcanxiang** [comment]
@Kelin-Hong 第一个明白了，感谢解疑.但是第二个问题，我集成到baseFragment里面，所有的onCreateView方法里面都调用transparent,但是还是一样的。所有的fragment布局都上到了状态栏。
阅读sample源码，感觉没什么区别.....

**Comment by zengcanxiang** [comment]
而且三个fragment，在第一个上面加fitsSystemWindows,恩，不上布局了，但是在第二个，第三个布局里面加这个属性，就没有效果..... 唉，只是测试，布局都是那种最简单的，一个linearLayout里面一个TextView

**Comment by Kelin-Hong** [comment]
可能是我的库有点bug，你试着在toolbar外面加上应该就可以了 ` <android.support.design.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="?attr/colorPrimary">

        <android.support.design.widget.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:theme="@style/AppTheme.AppBarOverlay"
            app:elevation="0dp">
            <android.support.v7.widget.Toolbar
                    android:id="@+id/toolbar"
                    android:layout_width="match_parent"
                    android:layout_height="?attr/actionBarSize"
                    android:background="?attr/colorPrimary"
                    app:popupTheme="@style/AppTheme.PopupOverlay"/>`

    </android.support.design.widget.AppBarLayout>
    .....
  </android.support.design.widget.CoordinatorLayout>

**Comment by zengcanxiang** [comment]
@Kelin-Hong 之前一段时间这个相关的项目没有去动.  
比较和你的代码之后，发现并不是布局文件有问题，而是我使用这样的代码添加fragment
```java 

 /**
     * 切换fragment(隐藏)
     */
    protected final void checkHide(int viewId, int showIndex) {
        List<Fragment> allFragment = bindFragment();
        FragmentTransaction b = hideAllFrag(showIndex);
        if (showIndex >= allFragment.size()) {
            Logger.e("showIndex >= allFragment.size()：showIndex=" + showIndex + ",allFragment.size()=" + allFragment.size());
            return;
        }
        Fragment fragment = allFragment.get(showIndex);
        if (!fragment.isAdded()) {
            b.add(viewId, fragment);
        }
        b.show(fragment);
        b.commit();
    }
```
而你的是replace,commit.并不知道为什么会导致这个问题...
